name: Delete

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      
#     - name: ansible-lint
#       uses: ansible/ansible-lint-action@master
#       with:
#         targets: "delete-aks.yaml"

#     - name: Uninstall Ansible 2.9
#       run: pip uninstall ansible

    - name: Install Ansible Azure
      run: pip install ansible[azure]
      
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZ_CREDENTIALS}}
            
    - name: Run Ansible Playbook
      run: ansible-playbook delete-aks.yaml -vvv
